-- decompiled by Sentinel (took 354.562µs)
local v1 = require(game:GetService("ReplicatedStorage"):WaitForChild("HDAdminSetup")):GetMain(true)
v1:Initialize("Client")
v1:GetModule("PageAbout"):UpdateRankName()
v1:GetModule("PageAbout"):UpdateProfileIcon()
v1:GetModule("PageAbout"):CreateUpdates()
v1:GetModule("PageAbout"):UpdateContributors()
v1:GetModule("PageAbout"):CreateCredits()
v1:GetModule("PageCommands"):CreateCommands()
v1:GetModule("PageCommands"):CreateMorphs()
v1:GetModule("PageCommands"):CreateDetails()
v1:GetModule("PageSpecial"):SetupDonorCommands()
v1:GetModule("PageAdmin"):SetupRanks()
v1:GetModule("GUIs"):DisplayPagesAccordingToRank()
local v2 = { v1.gui }
v1.contentProvider:PreloadAsync(v2)
